### ISSUE TITLE
Poc1to2Converter v.2.3 does not process the scoops when the "Speed boost" checkbox is checked

### ISSUE THREAD

**Issue by Shekelme** [JohnnyFFM/Poc1to2Converter#11]
Windows 7 x64, Ryzen 7 1700 CPU, 16 GB RAM. There is nothing going on in converter's window when when the "Speed boost" checkbox is checked. The process seems to be stucked at 0%. I opened second instance of converter to convert plot files on another disk without the "speed boost" checkbox, and it is simply working as it should to.

**Comment by Kafkamorph** [comment]
@Shekelme : It takes a while for progress to be visible.
Even when converting small plots (15G), completion says "0%" for a while, and one can only see progress when it reaches 12%. Then another pause, then 25%, 38%, and so forth.

Just because you can not see realtime progress does not mean it is not working.

**Comment by JohnnyFFM** [comment]
Exactly.. since it is processing several scoops at a time, it will take a while to have the first status update.

**Comment by Shekelme** [comment]
Well, then I'm sorry for that. My plots are 400 GB...
